NationalParks/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('natparks/', include('natparks.urls')),
    ]

natparks/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.PicNatParks.as_view()),
    path('api/', views.ListNatParks.as_view(), name='api'),
    path('api/<int:pk>/', views.DetailNatParks.as_view()),
]

natparks/models.py
from django.db import models
import requests


class NatParks(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    picture = models.ImageField(blank=True)
    location = models.URLField(blank=True)

    def __str__(self):
        """A string representation of the model."""
        return self.title


class NatParkGeo(models.Model):
    title = models.ForeignKey(NatParks, on_delete=models.CASCADE)
    postcode = models.IntegerField(blank=True, default=99999)
    calltitle = models.CharField(max_length=200)
    place = models.CharField(blank=True, max_length=128, default='paikka')
    state = models.CharField(blank=True, max_length=128, default='osav')
    kohdeLat = models.DecimalField(max_digits=10, decimal_places=8, default=64.12)
    kohdeLon = models.DecimalField(max_digits=12, decimal_places=8, default=-108.12)

    # def __str__(self):
    #     """A string representation of the model."""
    #     return self.calltitle

    def __str__(self):
        return str(self.postcode).zfill(5)

    def save(self, *args, **kwargs):
        kysely = requests.get(f'https://public.opendatasoft.com/api/records/1.0/search/?dataset=us-zip-code-latitude'
                              f'-and-longitude&q={self.postcode}&facet=state&facet=timezone&facet=dst')
        self.place = kysely.json()['records'][0]['fields']['city']
        self.state = kysely.json()['records'][0]['fields']['state']
        self.kohdeLat = kysely.json()['records'][0]['fields']['latitude']
        self.kohdeLon = kysely.json()['records'][0]['fields']['longitude']
        super().save(*args, **kwargs)

natparks/views.py
from django.views import generic
from rest_framework import generics

from NationalParks.settings import NASA_API_KEY
from .models import NatParks, NatParkGeo
from .serializers import NatParksSerializer


class ListNatParks(generics.ListCreateAPIView):
    queryset = NatParks.objects.all()
    serializer_class = NatParksSerializer


class DetailNatParks(generics.RetrieveUpdateDestroyAPIView):
    queryset = NatParks.objects.all()
    serializer_class = NatParksSerializer


class PicNatParks(generic.ListView):
    model = NatParks

    # def nasakey(self):
    #     nasakey = NASA_API_KEY
    #     return nasakey

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nasakey'] = NASA_API_KEY
        return context

natparks/templates/natparks/natparks_list.html
 <!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap 4 Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<style>
.flip-card {
  background-color: transparent;
  width: 300px;
  height: 360px;
  perspective: 1000px;
}

.flip-card-inner {
  position: relative;
  width: 100%;
  height: 100%;
  text-align: center;
  transition: transform 0.6s;
  transform-style: preserve-3d;
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
}

.flip-card:hover .flip-card-inner {
  transform: rotateY(180deg);
}

.flip-card-front, .flip-card-back {
  position: absolute;
  width: 100%;
  height: 100%;
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
}

.flip-card-front {
  background-color: #bbb;
  color: black;
}

.flip-card-back {
  background-color: lightgrey;
  {#color: white;#}
  transform: rotateY(180deg);
}
</style>

<body>

Check also an <a href="{% url 'api' %}"><b>API</b></a>

{% load static %}
     <div class="container">
         <div class="card-columns">
            {% for kuva in object_list %}
                    <div class="card-body flip-card">
                        <div class="flip-card-inner">
                            <div class="flip-card-front">
                                <img class="rounded img-fluid" src="{% static "images/" %}{{ kuva.picture }}">
                            </div>
                            <div class="flip-card-back">
                                <p>{{ kuva.title}}</p>
                                <small>
                                <p>{{ kuva.description}}</p>
                                </small>
                                <a href='{{ kuva.location }}' target="_blank">Lisätietoja</a>
                                <a href="https://api.nasa.gov/planetary/earth/imagery?lon={{ kuva.natparkgeo_set.get.kohdeLon }}
                                &lat={{ kuva.natparkgeo_set.get.kohdeLat }}&dim=0.15&api_key={{ nasakey }}" target="_blank">
                                    Sateliittikuva</a>
                            </div>
                        </div>
                    </div>
            {% endfor %}
         </div>
     </div>
</body>
</html>